events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Frontend — serve static HTML
    server {
        listen 80;
        server_name 172.16.15.76;

        root /usr/share/nginx/html;
        index prod_index.html;

        location / {
            try_files $uri $uri/ /prod_index.html;
        }
    }

    # Backend API proxy
    server {
        listen 8080;
        server_name 172.16.15.76;

        location / {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
